apiVersion: apps/v1
kind: Deployment
metadata:
  name: deals-service-config-map
  namespace: 'namespace_update_here'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deals-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deals-service
    spec:
      containers:
        - args:
            - >
              sh /opt/application/env-deals.sh && node --require
              '@opentelemetry/auto-instrumentations-node/register' dist/main.js
          command:
            - sh
            - '-c'
          env:
- name: deals-service-config-map
            - name: deals-service-config-map
              value: 'http://otel-collector.monitoring.svc:4318'
            - name: deals-service-config-map
              value: http/protobuf
            - name: deals-service-config-map
              value: deals-service
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
            - name: deals-service-config-map
              valueFrom:
                configMapKeyRef:
                  key: 
                  name: deals-service-config-map
          image: 'repository_name_update_here:image_tag_update_here'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '60'
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          name: deals-service-config-map
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
      serviceAccountName: default
      terminationGracePeriodSeconds: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deals-service-config-map
  namespace: 'namespace_update_here'
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: deals-service-config-map
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deals-service-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: deals-service-config-map
  namespace: 'namespace_update_here'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: deals-service
  sessionAffinity: None
  type: ClusterIP
 
